language: python
python:
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: aubricus
  password:
    secure: aBU5meitejEYrvE8rCTxfWfqthLNVnxrEkNc5KS7RRiK46g3GWz55kP8H7pcTkkTDYwd5hMgCLGqRC/lwFG8ftKenizTqro2s3xpKfrI+DHWW9XhdtrOJehVdySgYD1X3Hwoth2my9yv/q1T5anNkR0cthIlFkBo6fduhJV3bGCkgjE5Oc1R8RgDc3TuqQ23tkDen+3AXjcZ07vXIqUEQ4CH/PVEcB+20ppNHYGOOzcNLjLmKjAfsFco2IZBU+Sbc6IqoEMzcVrY1cuv0eBQ5MPxiXnoJUIndo69FyilgXoPSORrmYrLSMPf+B+AMZTMThY2D3fQpsWu2mSwb5i512dh/FoaW8Obd6zTBBzJSbdy7qvEf2uuR2gXttz5IZEKtwCTp5CZoE+KYz6qYRr1fptvn2KhP8TpLSGE6/cq9Sq9PAwxrjEbZE81k7bMhTvz7qvRr6dYgYYcdQFNbnv+ltNTd7FIuuk5YbUZDvhzuLGDyq2HRW40ARt60HaYYZj3XoTkx6paiJGufUjWFPVwQykJ6rSTXUmkL3I3NPRr5Aex8olEkX3onKi3zC0apVNsLPLCDhK4ijxJzUp4W3gLWqQmSnc09Hzdh1i63FpE1uLaNM7dNXSpwv3bDfhFiaSL9OKThoHohKRhpMDTT7lSaiw8J+8mRvGuMU7jLf/z3z8=
  on:
    tags: true
    repo: aubricus/klak
    python: 3.6
